//! The service side: what an integration exports, and how a call finds it.
//!
//! An integration implements [`Interface`] — usually by writing a normal `impl`
//! block and putting `#[tinybus::interface]` on it — and registers instances at
//! [`ObjectPath`](crate::name::ObjectPath)s on its connection. Dispatch is then
//! `path → interface → member`, in that order, with a distinct error at each
//! step so a caller can tell "that integration isn't running" from "that
//! integration is running an older contract".
//!
//! # Why the trait takes and returns [`Value`]
//!
//! Typed dispatch is what the macro *generates*; the trait underneath has to be
//! object-safe, because one connection holds a heterogeneous list of interfaces
//! behind `dyn`. The macro turns a typed Rust signature into an argument
//! deserialize, a call, and a return serialize — so the handwritten code is
//! typed and only the seam is dynamic.

pub mod tree;

#[cfg(test)]
#[path = "macro_tests.rs"]
mod macro_test;

use async_trait::async_trait;
use serde_json::Value;

use crate::error::Result;
use crate::name::{BusName, InterfaceName, MemberName};

pub use crate::service::tree::ObjectTree;

/// Transport-authenticated facts about one incoming method call.
///
/// A sender identifies a connection in this broker session, never a human or
/// an artifact. Bind it to trusted initialization separately. This type has no
/// wire representation and no public constructor for authenticated identity.
/// Direct dispatch and transports without proven broker routing are unverified.
/// Memory deliveries carry a private broker proof; custom transports and Unix
/// sockets remain unverified even after Hello. Native SDK deliveries require a
/// trusted host's additive C routing callback. Confidential recipient attestation
/// is separate from incoming sender authentication. Invalidate any binding on
/// disconnect or broker replacement; names are unique only within one session.
///
/// Authority cannot be deserialized from invocation JSON:
/// ```compile_fail
/// let _: tinybus::CallContext = serde_json::from_str("{}").unwrap();
/// ```
#[derive(Debug, Clone, Default)]
pub struct CallContext {
    sender: Option<BusName>,
}

impl CallContext {
    /// The broker-stamped unique sender, only on a proven broker delivery path.
    pub fn authenticated_sender(&self) -> Option<&BusName> {
        self.sender.as_ref()
    }

    pub(crate) fn brokered(sender: Option<&BusName>) -> Self {
        Self {
            sender: sender.filter(|name| name.is_unique()).cloned(),
        }
    }
}

/// One contract a service implements.
///
/// Use `#[tinybus::interface]` for ordinary typed methods. Implement by hand for
/// dynamic bridges or to authorize incoming calls with `call_with_context`;
/// context never becomes an extra positional argument.
#[async_trait]
pub trait Interface: Send + Sync + 'static {
    /// The interface's name, e.g. `ai.tinyhumans.openhuman.Voice`.
    fn name(&self) -> InterfaceName;

    /// Every member this interface dispatches, for introspection.
    ///
    /// `tinybus call` uses it to fail fast with the available members listed,
    /// which is the difference between a typo taking ten seconds and ten
    /// minutes.
    fn members(&self) -> Vec<MemberName>;

    /// Whether `member` refuses an ordinary, monitor-visible call.
    ///
    /// Implementations generated by [`tinybus_macros::interface`] return
    /// `true` for methods annotated with `#[tinybus(confidential)]`. Dynamic
    /// interfaces remain ordinary by default.
    fn requires_confidential(&self, _member: &MemberName) -> bool {
        false
    }

    /// Run `member` against `args`, a positional JSON array.
    ///
    /// Returning `Err` is normal and expected: it becomes an error reply, and
    /// the caller sees [`crate::Error::MethodFailed`] carrying
    /// [`crate::Error::wire_name`]. A panic, by contrast, takes the whole
    /// service down — [`crate::connection::Connection`] does not catch unwinds,
    /// because a service that has panicked has an unknown internal state and
    /// answering the next call from it is worse than being restarted.
    async fn call(&self, member: &MemberName, args: Value) -> Result<Value>;

    /// Run a call with transport-authenticated incoming facts.
    ///
    /// Context is out of band: positional arguments and legacy implementations
    /// stay unchanged. Override this method to authorize callers; an unverified
    /// context must fail closed when caller identity is required.
    async fn call_with_context(
        &self,
        member: &MemberName,
        args: Value,
        _context: &CallContext,
    ) -> Result<Value> {
        self.call(member, args).await
    }
}

#[async_trait]
impl<T: Interface + ?Sized> Interface for std::sync::Arc<T> {
    fn name(&self) -> InterfaceName {
        (**self).name()
    }

    fn members(&self) -> Vec<MemberName> {
        (**self).members()
    }

    fn requires_confidential(&self, member: &MemberName) -> bool {
        (**self).requires_confidential(member)
    }

    async fn call(&self, member: &MemberName, args: Value) -> Result<Value> {
        (**self).call(member, args).await
    }

    async fn call_with_context(
        &self,
        member: &MemberName,
        args: Value,
        context: &CallContext,
    ) -> Result<Value> {
        (**self).call_with_context(member, args, context).await
    }
}

#[cfg(test)]
#[path = "mod_tests.rs"]
mod tests;
